# Generated by Django 3.1 on 2020-09-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='notification',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='viewed_messages',
            name='sms_notification',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='viewed_messages',
            name='status_view',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
