# Generated by Django 2.2.6 on 2020-03-17 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_viewed_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewed_messages',
            name='id_SMS',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='my_app.Sms_message'),
            preserve_default=False,
        ),
    ]
