# Generated by Django 2.2.6 on 2020-06-24 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_viewed_messages_id_sms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ps',
            name='controller',
        ),
        migrations.DeleteModel(
            name='Gsm_controller',
        ),
    ]
