# Generated by Django 2.2.6 on 2020-12-07 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_app', '0004_ps_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=12, verbose_name='Номер')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('text_sms', models.TextField(verbose_name='Текст сообщения')),
            ],
            options={
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='ViewedMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_view', models.BooleanField(verbose_name='Просмотрено')),
                ('datetime_view', models.DateTimeField(blank=True, verbose_name='Дата просмотра')),
                ('sms_notification', models.BooleanField(verbose_name='СМС уведомление')),
                ('id_SMS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.SmsMessage', verbose_name='СМС')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name_plural': 'Квитирование',
            },
        ),
        migrations.RemoveField(
            model_name='viewed_messages',
            name='id_SMS',
        ),
        migrations.RemoveField(
            model_name='viewed_messages',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='ps',
            options={'verbose_name_plural': 'Подстанции'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='notification',
            field=models.BooleanField(verbose_name='уведомление'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_num_for_notif',
            field=models.CharField(help_text='вводить через запятую', max_length=150, verbose_name='номера для оповещения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='ps',
            name='is_active',
            field=models.BooleanField(verbose_name='В сети'),
        ),
        migrations.AlterField(
            model_name='ps',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='ps',
            name='res',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='РЭС'),
        ),
        migrations.AlterField(
            model_name='ps',
            name='tel_number',
            field=models.CharField(max_length=12, verbose_name='Номер СИМ'),
        ),
        migrations.DeleteModel(
            name='Sms_message',
        ),
        migrations.DeleteModel(
            name='Viewed_messages',
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='ps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.Ps', verbose_name='ПС'),
        ),
    ]
