# Generated by Django 2.2.6 on 2020-12-07 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_auto_20201207_1412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'Расширение профилей'},
        ),
    ]
