# Generated by Django 2.2.6 on 2020-08-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_auto_20200624_2326'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.RenameField(
            model_name='viewed_messages',
            old_name='status',
            new_name='sms_notification',
        ),
        migrations.AddField(
            model_name='ps',
            name='phone_num_for_notif',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='viewed_messages',
            name='datetime_view',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viewed_messages',
            name='status_view',
            field=models.NullBooleanField(),
        ),
    ]
