# Generated by Django 2.2.6 on 2020-08-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_auto_20200826_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ps',
            name='phone_num_for_notif',
        ),
        migrations.AddField(
            model_name='res',
            name='phone_num_for_notif',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
