# Generated by Django 2.2.6 on 2020-08-31 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_auto_20200831_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Res',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='ps',
            name='res',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.Res'),
        ),
    ]
