# Generated by Django 2.2.6 on 2020-09-23 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controller_type',
            fields=[
                ('type', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Signal_status',
            fields=[
                ('status', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Signal_type',
            fields=[
                ('type', models.CharField(max_length=12, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Voltage',
            fields=[
                ('value', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SIM_card_number',
            fields=[
                ('number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signal_PS.Provider')),
            ],
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('date_up', models.DateTimeField()),
                ('ps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.Ps')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signal_PS.Signal_status')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signal_PS.Signal_type')),
                ('voltage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='signal_PS.Voltage')),
            ],
        ),
        migrations.CreateModel(
            name='Gsm_controller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50)),
                ('add_description', models.TextField()),
                ('number_SIM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signal_PS.SIM_card_number')),
                ('ps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.Ps')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signal_PS.Controller_type')),
            ],
        ),
    ]
