# Generated by Django 2.2.6 on 2020-09-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal_PS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='inversion',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signal_status',
            name='boolean_status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
