# Generated by Django 2.2.6 on 2020-06-24 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_viewed_messages_id_sms'),
        ('signal_PS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controller_type',
            fields=[
                ('type', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='signal',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='SIM_card_number',
            fields=[
                ('number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signal_PS.Provider')),
            ],
        ),
        migrations.CreateModel(
            name='Gsm_controller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50)),
                ('add_description', models.TextField()),
                ('number_SIM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signal_PS.SIM_card_number')),
                ('ps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.Ps')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signal_PS.Controller_type')),
            ],
        ),
    ]
