# Generated by Django 2.2.6 on 2020-09-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal_PS', '0002_auto_20200930_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signal',
            name='inversion',
        ),
        migrations.AddField(
            model_name='signal_type',
            name='inversion',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
