# Generated by Django 2.2.6 on 2020-09-22 11:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('signal_PS', '0003_auto_20200917_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='date_up',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
